### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ShadowGaming100** [tasinone/dnscontrol#1]
i can help you to make this working if you need help because i am using it and make sure to make it private

**Comment by tasinone** [comment]
> i can help you to make this working if you need help because i am using it and make sure to make it private

Thank you so much bro that you want to help me. I have already fixed it but I want to know how did you do it. So how can we talk?

**Comment by ShadowGaming100** [comment]
> > i can help you to make this working if you need help because i am using it and make sure to make it private
> 
> Thank you so much bro that you want to help me. I have already fixed it but I want to know how did you do it. So how can we talk?

How do you want to talk

**Comment by ShadowGaming100** [comment]
Discord??

**Comment by tasinone** [comment]
> Discord??

Yeah! Discord is fine. Mine is "tasinone" and the name is Kakarot.

**Comment by ShadowGaming100** [comment]
> tasinone

ok

**Comment by ShadowGaming100** [comment]
> > Discord??
> 
> Yeah! Discord is fine. Mine is "tasinone" and the name is Kakarot.

sent name Shadow Gaming
